 const imagesData = [
    'https://lexica.art/prompt/bcf2a46f-fd8a-4a1a-9045-52824292ff93',
    './images/1.png',
    './images/01.png',
    './images/2.png',
    './images/02.png',
    './images/03.png',
    './images/g0.png',
    './images/a.png',
    './images/a3.png',
    './images/3.png',
    './images/4.png',
    './images/04.png',
    './images/5.png',
    './images/6.png',
    './images/06.png',
    './images/7.png',
    './images/8.png',
    './images/07.png',
    './images/08.png',
    './images/g1.png',
    './images/.png',
    './images/09.png',
    './images/a4.png',
    './images/9.png',
]
export default imagesData;